<a href="https://colab.research.google.com/github/dahlia52/Advanced-Statistical-Data-Analysis/blob/main/torch_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sys
import numpy as np
import torch
import torch.nn as nn

In [ ]:
print(sys.version)
print(np.__version__)
print(torch.__version__)

3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
1.23.5
2.0.1+cu118


In [ ]:
# !pip install torch==1.13.1

In [ ]:
available_gpu = [torch.cuda.device(i) for i in range(torch.cuda.device_count())]

In [ ]:
print(available_gpu)
print(len(available_gpu))

1


In [ ]:
# device0 = torch.device("cuda:0")
device0 = torch.device("cuda:0" if torch.cuda.is_available() else 'cpu')
# device0 = torch.device("mps:0" if torch.backends.mps.is_available() else 'cpu') # m1/m2/mac

In [ ]:
device0

device(type='cuda', index=0)

In [ ]:
a_np = np.random.randn(2,3,4)
b = torch.randn(3,4)

In [ ]:
a_np

array([[[ 0.46663722,  0.67122192,  0.26786148, -0.52164903],
        [-1.22057252, -1.88634861, -0.43874637, -0.88196492],
        [ 2.14972571, -0.00990101,  0.63194299, -0.65125494]],

       [[-0.50246507, -0.97409498,  0.01787318, -0.20269111],
        [-0.03004556,  0.33737973,  1.90565462, -0.46283841],
        [ 0.30532597, -0.31866606, -0.48510649,  0.0380892 ]]])

In [ ]:
b

tensor([[-1.3305,  1.2656,  1.1461,  0.0550],
        [ 0.7428, -0.2982,  0.7659,  1.0880],
        [ 1.6658, -1.2286, -2.9042, -0.6774]])

In [ ]:
print(type(a_np))
print(type(b))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>


In [ ]:
print(a_np + b) # numpy + tensor 계산 안됨

TypeError: ignored

In [ ]:
print(b + a_np)

tensor([[[-0.8638,  1.9368,  1.4140, -0.4666],
         [-0.4778, -2.1845,  0.3272,  0.2061],
         [ 3.8156, -1.2385, -2.2722, -1.3287]],

        [[-1.8329,  0.2915,  1.1640, -0.1477],
         [ 0.7128,  0.0392,  2.6716,  0.6252],
         [ 1.9712, -1.5473, -3.3893, -0.6393]]], dtype=torch.float64)


In [ ]:
a = torch.tensor(a_np) # tensor로 변환

In [ ]:
print(a+b)

tensor([[[-0.8638,  1.9368,  1.4140, -0.4666],
         [-0.4778, -2.1845,  0.3272,  0.2061],
         [ 3.8156, -1.2385, -2.2722, -1.3287]],

        [[-1.8329,  0.2915,  1.1640, -0.1477],
         [ 0.7128,  0.0392,  2.6716,  0.6252],
         [ 1.9712, -1.5473, -3.3893, -0.6393]]], dtype=torch.float64)


In [ ]:
b_np = b.numpy() # numpy로 변환

In [ ]:
print(a_np + b_np) # numpy + numpy

[[[-0.86383453  1.93679459  1.41399121 -0.46663936]
  [-0.47776936 -2.18451199  0.32715603  0.20608449]
  [ 3.81555489 -1.23853358 -2.27223349 -1.32866268]]

 [[-1.83293682  0.29147769  1.16400291 -0.14768144]
  [ 0.71275759  0.03921635  2.67155702  0.625211  ]
  [ 1.97115515 -1.54729863 -3.38928297 -0.63931854]]]


In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
b = b.to(device0) # gpu에 올림

In [ ]:
print(b)

tensor([[-1.3305,  1.2656,  1.1461,  0.0550],
        [ 0.7428, -0.2982,  0.7659,  1.0880],
        [ 1.6658, -1.2286, -2.9042, -0.6774]], device='cuda:0')


In [ ]:
print(a+b) # a는 cpu, b는 gpu 위에 있으므로 계산 안 됨.

RuntimeError: ignored

In [ ]:
a = torch.tensor(a_np).to(device0) # a를 gpu에 올림

In [ ]:
print(a+b)

tensor([[[-0.8638,  1.9368,  1.4140, -0.4666],
         [-0.4778, -2.1845,  0.3272,  0.2061],
         [ 3.8156, -1.2385, -2.2722, -1.3287]],

        [[-1.8329,  0.2915,  1.1640, -0.1477],
         [ 0.7128,  0.0392,  2.6716,  0.6252],
         [ 1.9712, -1.5473, -3.3893, -0.6393]]], device='cuda:0',
       dtype=torch.float64)


In [ ]:
!nvidia-smi

Wed Sep 13 04:50:12 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   61C    P0    27W /  70W |    601MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
print(b.shape)

torch.Size([3, 4])


In [ ]:
print(b.dim())

2


In [ ]:
print(a.dim())

3


In [ ]:
c = torch.zeros(5,4)

In [ ]:
print(c)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [ ]:
d = torch.ones(5,4)

In [ ]:
print(d)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [ ]:
e = torch.eye(3)

In [ ]:
print(e)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [ ]:
f = torch.zeros_like(b) # b와 같은 shape인 array

In [ ]:
print(f)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], device='cuda:0')


In [ ]:
a

tensor([[[ 0.4666,  0.6712,  0.2679, -0.5216],
         [-1.2206, -1.8863, -0.4387, -0.8820],
         [ 2.1497, -0.0099,  0.6319, -0.6513]],

        [[-0.5025, -0.9741,  0.0179, -0.2027],
         [-0.0300,  0.3374,  1.9057, -0.4628],
         [ 0.3053, -0.3187, -0.4851,  0.0381]]], device='cuda:0',
       dtype=torch.float64)

In [ ]:
a = a.cpu()

In [ ]:
print(a)

tensor([[[ 0.4666,  0.6712,  0.2679, -0.5216],
         [-1.2206, -1.8863, -0.4387, -0.8820],
         [ 2.1497, -0.0099,  0.6319, -0.6513]],

        [[-0.5025, -0.9741,  0.0179, -0.2027],
         [-0.0300,  0.3374,  1.9057, -0.4628],
         [ 0.3053, -0.3187, -0.4851,  0.0381]]], dtype=torch.float64)


In [ ]:
b = b.cpu()

In [ ]:
print(a+b)

tensor([[[-0.8638,  1.9368,  1.4140, -0.4666],
         [-0.4778, -2.1845,  0.3272,  0.2061],
         [ 3.8156, -1.2385, -2.2722, -1.3287]],

        [[-1.8329,  0.2915,  1.1640, -0.1477],
         [ 0.7128,  0.0392,  2.6716,  0.6252],
         [ 1.9712, -1.5473, -3.3893, -0.6393]]], dtype=torch.float64)


In [ ]:
g = torch.ones_like(a)

In [ ]:
print(g)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]], dtype=torch.float64)


In [ ]:
a = a.to(device0)